### ISSUE TITLE
Using Buddy press registration process not working

### ISSUE THREAD

**Issue by radoslavrade** [strangerstudios/pmpro-buddypress#10]
I set everything but the buddy press checkout registration option wont work, when i access buddy press registration page, there is no section for membership choice or anything connected to paid membership pro.

**Comment by ideadude** [comment]
Neither PMPro core or this add on adds the PMPro level select to the BuddyPress registration screen.

You can setup a 2 step process where users register in BuddyPress first and then you direct them to the PMPro levels page (or a specific level checkout page) to complete PMPro checkout.
