### ISSUE TITLE
Conflict with BuddyBoss Pro Plugin

### ISSUE THREAD

**Issue by nookale** [strangerstudios/pmpro-buddypress#107]
Conflict between this Plugin and BuddyBoss Pro Plugin.

File groups.php functions:

- pmpro_bp_nouveau_get_group_meta_custom <= Remove the group status in meta if one is present 
- pmpro_bp_get_group_type_custom <= Remove the group type if one is present

Removes important information that should have been added to the Group Directory and Group Single front end (private/public, type of group)

Why is this behavior (removing meta and group type) necessary? Could this plugin be made compatible with BuddyBoss Pro Plugin? 

Thanks!

**Comment by andrewlimaza** [comment]
To remove this behavior, please add the following lines of code to your site (to unhook these functions):

`
function my_pmpro_bp_remove_functionality() {
    remove_filter( 'bp_nouveau_get_group_meta', 'pmpro_bp_nouveau_get_group_meta_custom', 10, 3 );
    remove_filter( 'bp_get_group_type', 'pmpro_bp_get_group_type_custom' );
}
add_action( 'init', 'my_pmpro_bp_remove_functionality' );
`

**Comment by andrewlimaza** [comment]
I've made a decision to keep this disabled by default and developer's can opt-into it. It can be confusing whichever way we go with this decision. It will be disabled from the next release.
