### ISSUE TITLE
Add support for PMPro Approvals and PMPro Pay by Check

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-buddypress#12]

**Comment by andrewlimaza** [comment]
I have just tested this and to give further feedback about the PMPro Approvals issue.

Approved members still get redirected to "Access Restricted" page. 

It restricts fine with certain settings of the Approvals Add On.

**Comment by andrewlimaza** [comment]
User's have said that their content doesn't restrict for pending approval users. Still testing this.

**Comment by ideadude** [comment]
Should be fixed in v1.1 by this comitt https://github.com/strangerstudios/pmpro-buddypress/commit/bad44f4fa1bfc18cd95d1dfda8a901ab90349d6f

**Comment by ideadude** [comment]
I believe we need to double check pmpro_hasMembershipLevel again here to get this fix working when using the Lock All of BuddyPress option.

https://github.com/strangerstudios/pmpro-buddypress/blob/e5bc3b1e5084e9f6ae9a1621959fce889e61ee3a/includes/restrictions.php#L172

**Comment by JarrydLong** [comment]
Support for the Approvals Add On is being taken care of in https://github.com/strangerstudios/pmpro-buddypress/issues/71
