### ISSUE TITLE
cause white page in case of buddypress deactivated.

### ISSUE THREAD

**Issue by alexlii1971** [strangerstudios/pmpro-buddypress#14]
Hello,

1. multisite, and buddypress networkly activated.
2.I assign a forum subsite as BP main site.  please check https://codex.buddypress.org/getting-started/installation-in-wordpress-multisite/, that means I use B method.
3. in woo commerce subsite, pmpro-buddypress is activated.

By this setup, only users who purchase a membership product will automatically enter into the level BP group.

in this case, if buddypress is deactivated, the woo commerce site will be white page.
I can understand the reason, but it would be much better if you can avoid.

Thanks.

Alex

**Comment by pbrocks** [comment]
To debug this, why not add something like this to the bottom of your wp-config.php. Notice, I've included the last line of wp-config.php, so please don't duplicate.
`/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';

if ( ! defined( 'BP_REQUIRED_PHP_VERSION' ) ) {
	echo '<h2 style="text-align:center;">You need to activate BuddyPress</h2>';
} else {
	echo '<h2 style="text-align:center;">BuddyPress is ON!!</h2>';
	define( 'BP_ROOT_BLOG', $blog_id );
}
`
Also please note that you will need to remove your constant definition for the BuddyPress subsite blog. Now, with this debug code, you'll have a message in the head of every page. When you're comfortable with how the snippet works, you can remove the echo statements and adjust further to meet your needs.

**Comment by greathmaster** [comment]
BuddyPress is disabled, PMPro BuddyPress should not be the cause of a white screen.
