### ISSUE TITLE
Redirect instead of unworking button

### ISSUE THREAD

**Issue by ZenzeAlmere** [strangerstudios/pmpro-buddypress#15]
Is it possible to redirect a button to the members levels-page instead of just blocking the button

**Comment by pbrocks** [comment]
@ZenzeAlmere We'll need more information about this. What button? Can you give a screenshot?

**Comment by ideadude** [comment]
These recent updates address this:

https://github.com/strangerstudios/pmpro-buddypress/commit/08385efc58dda0ff4b45dfb4633d2110547dfb49

https://github.com/strangerstudios/pmpro-buddypress/commit/2eede85c556125b5f5051e91575bd8a4706cfd23

I will close this issue. Let me know if you are still having trouble. Feel free to open a new issue with specific details.
