### ISSUE TITLE
Add membership information on the BuddyPress profile page

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-buddypress#22]
We should look at adding action links for PMPro on the BuddyPress profile page as a user has requested that they do not want more than one 'profile' page.

I think this could be a great feature to this Add On.

**Comment by alexlii1971** [comment]
it would be great.

For me, I networkly activated BP and assign "Forum" site as Bp main site. and activated pmpro-buddypress in Shop subsite, and I ask site users pay for membership by Mycred point on shop site.

In this situation,  will the membership information  be shown up on user BP profile at forum site?


Thanks

Alex

**Comment by andrewlimaza** [comment]
@alexlii1971 I've done a variation of this feature request, it will include the membership account page within the BuddyPress profile page. This way we isolate and reuse default code from PMPro and keep it as stable as possible.
