### ISSUE TITLE
Active members not showing in BuddyPress members area.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-buddypress#24]
If user's have an active membership level but the level is set to "Disable New Signups". User's don't show up in the BuddyPress members list.

As soon as you enable new signups, members show up in the BuddyPress members list again.

**Comment by ideadude** [comment]
Simple fix here https://github.com/strangerstudios/pmpro-buddypress/commit/b4cd66cc3eee06617794f29b877ec2b1705bbbc1

Going out in next release.
