### ISSUE TITLE
Bug: Unexpected behavior on friend request tab 

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-buddypress#29]
There is an unexpected behavior related to the friend request tab. Specifically, members are showing in some cases that should not be there. This is detailed further in the support post:

https://www.paidmembershipspro.com/forums/topic/friend-requests-tab-bug/

The issue revolves around the update introduced in Version 1.1.1 which modified the query in `pmpro_bp_bp_pre_user_query_construct`.

**Comment by pbrocks** [comment]
Same issue here: https://www.paidmembershipspro.com/forums/topic/buddypress-all-members-friend-request/#post-166560

**Comment by greathmaster** [comment]
According to the private support ticket: https://www.paidmembershipspro.com/forums/topic/major-issue-with-paid-memberships-pro-buddypress-add-on/

This is also occurring when showing members in groups. Thinking this could be a wider issue whenever we have any type of member based query.

**Comment by ideadude** [comment]
I looked into this a bit and couldn't actually figure out how or why the SQL filter we were using would affect the friend request query.

In any case, it's possible to just check that we're within the "friends" component to short circuit the filter and that works. https://github.com/strangerstudios/pmpro-buddypress/commit/ec779c8393606e09ff6b35b0443a33216f03deb8

This will go out in the next update.
