### ISSUE TITLE
wp_pmpro_memberships_users WHERE membership_id IN () AND status = ‘active'”

### ISSUE THREAD

**Issue by alexlii1971** [strangerstudios/pmpro-buddypress#30]
Hello,

this issue or error log:
https://wordpress.org/support/topic/does-not-work-for-me-31/

This could be reprduced in the following case:

1.# In multisite, networkly activated buddypress, but set a sub site as buddypress primary site, let us say B site or forum.mysite.com;
2.# In another subsite, let us say A site or shop.mysite.com, in this sub site, woocommerce, Paid Memberships Pro and Paid Memberships Pro – BuddyPress Add On are all activated.

I want the user who shop a product will be automatically added into a specific group, basically it works well, but there will exactly same error produced, and the most important is that this error issue will caused one of our payment gateway does not work, and I have to deactivate it now.

So, it would be great if you could fixed it.

Thanks.
Alex

**Comment by ideadude** [comment]
We need to figure out if there is a bug in PMPro BuddyPress that keeps it from working in multisite setups or if this is a bug specific to this setup.

We don't officially support multisite for this plugin. It seems like it would be difficult to have a WC checkout on one subsite work through PMPro WooCommerce and a PMPro level on the same or maybe another subsite trigger a user to be added to a group on yet another subsite.

**Comment by alexlii1971** [comment]
Hello, it works now, I mean a user could be added into groups after buy multiple memberships levels products in ONE TIME.

The only issue now is that, if deleting the users in PMP user list,  those users will not be added into member user list and not be added into buddypress groups when they pay for new Membership products.

It is not a big issue for us, but still it would be great if you could fix that issue.

Thanks

**Comment by ideadude** [comment]
This SQL error comes up on single site installs as well. I am not sure if it affects the member directory results yet, but we should at least avoid the error. Fixing it may fix the MU issue as well.

**Comment by greathmaster** [comment]
This occurs when there are no restrictions on directory inclusion. so the `...WHERE membership_id IN ()` results in an error since `IN ()` is empty. We could return `false`, if the array `$include_levels` is empty.

**Comment by JarrydLong** [comment]
Tested this on the latest version of PMPro BuddyPress (1.2.9) and this appears to be working as expected. Unable to replicate for now
