### ISSUE TITLE
Feature Request: BuddyPress Add-on setting changes

### ISSUE THREAD

**Issue by AnsieLima** [strangerstudios/pmpro-buddypress#31]
Allow non-member to send a message but restrict them from reading the messages.

Request from user:
"Could you make a split in the BuddyPress Add-On Settings so I could allow a non-member to send a message but restrict them from reading the messages?
This would be much more productive than restrict the full message system to non-members"

**Comment by andrewlimaza** [comment]
Closing this, I don't think we will be doing this - a developer will be needed to customize this.
