### ISSUE TITLE
"No-Use non member settings" option not working

### ISSUE THREAD

**Issue by preferencex** [strangerstudios/pmpro-buddypress#33]
Hi, I'm using Paid Memberships Pro - BuddyPress Add On and when I choose the option "No-Use non member settings" in BuddyPress Restrictions section doesn't fix that option. If I edit again I will see other option choosed, usualy the last one.
Can you please help me?
Thank you

**Comment by ideadude** [comment]
Sorry for the slow fix on this. Fixed here: https://github.com/strangerstudios/pmpro-buddypress/commit/a9b35019873a25271c7fd70d4c48e7e53c69c0b1

And will be in the next update going out soon.

**Comment by preferencex** [comment]
Thank you =)



Com os melhores cumprimentos,


Francisco Coelho
www.fc.provider.pt <https://fc.provider.pt/>


Em qui, 3 de jan de 2019 às 19:34, Jason Coleman <notifications@github.com>
escreveu:
