### ISSUE TITLE
Updating User Profile Fields Groups Displays 

### ISSUE THREAD

**Issue by eviolini** [strangerstudios/pmpro-buddypress#34]
On a staging site in SiteGround running PHP 7.1.25 / WP 5.02 / PMP 2.0 AND PHP 7.1.25 / WP 4.9.9 / PMP 1.9.56 Memberlite 4.0

Behavior — When adding data to profile field groups in the profile on the front end, the page goes white and displays only a list of the field names in a continuous line in the header. By removing everything after /profile in the URL you get back to the profile page and the information entered has been saved and the profile displays correctly.

In the console the error is "Failed to load resource: the server responded with a status of 404 ()" with the link to the profile fields for this entry.

Expected behavior — The profile page should display on save, not the white page.

**Comment by pbrocks** [comment]
It looks like the function where the profile.php wants to sync  the xProfile, there is an[ `echo` function](https://github.com/strangerstudios/pmpro-buddypress/blob/dev/includes/profiles.php#L56), which, when removed, fixed the issue.

**Comment by eviolini** [comment]
Thank you. That patch works to get to the expected behavior.

**Comment by ideadude** [comment]
Fixed https://github.com/strangerstudios/pmpro-buddypress/commit/386fc2ddd6f7ac2aca86df97375a85c91bbe0cbc

Thanks
