### ISSUE TITLE
how to enable "Show Membership Level on BuddyPress Profile?"

### ISSUE THREAD

**Issue by alexlii1971** [strangerstudios/pmpro-buddypress#35]
Hello,

There is an setting option on Pmpro-buddypress: Show Membership Level on BuddyPress Profile.

and we are using the theme of Kleo: https://themeforest.net/item/kleo-pro-community-focused-multipurpose-buddypress-theme/6776630?s_rank=1

but I am not sure why the membership level does not show up, is it theme-related please? or any special setting needed please?

Thanks and have a nice day.

**Comment by andrewlimaza** [comment]
Sharing some results from recent tests, depending on your plugin (BuddyBoss or a variation thereof) as well as themes, this may not use the default BuddyPress filter for the profile page.

To show content in BuddyBoss, the best may be to use the following snippet in your customizations plugin:

`add_action( 'bp_member_header_actions', 'pmpro_bp_show_level_on_bp_profile' );`
