### ISSUE TITLE
Bug: Non-member users can still create groups if "Group Creation" is not allowed.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-buddypress#37]
Non-member users can still create groups from the "Create A New Group" page, even if "Group Creation" is set to "No" in PMPro BuddyPress settings. This restriction only hides the Create Group button.

**Comment by kimcoleman** [comment]
Just received an email support about this issue. I tested on my local and I am also able to recreate the bug. I can access the groups creation page directly (/groups/create/step/group-details/) and I also see the tab to "Create a Group" on the /groups/ page.

**Comment by kimwhite** [comment]
This is still an issue. Confirmed on BuddyPress and BuddyBoss page.
If using BuddyBoss, it has a setting that will disallow Creating Groups except for admins.

**Comment by kimwhite** [comment]
Not only Non-Members but Members Level you have marked "no" to also

**Comment by andrewlimaza** [comment]
I've tested this, issue seems to be resolved. Create a New Group is set to "No" for non-members and this option is hidden entirely.

I am going to leave this issue open for a bit as we work through this next release.
