### ISSUE TITLE
HTML email styling not working

### ISSUE THREAD

**Issue by TheAwoken** [strangerstudios/pmpro-buddypress#44]
Hi,
when I deactivate PMPro everything works great, and I am getting HTML emails from BuddyPress, 
but as soon as I activate PMPro again, the email HTML styling is gone.

can anyone help me with that?
thanks

**Comment by andrewlimaza** [comment]
You could try this code - https://gist.github.com/andrewlimaza/cc6d1c2f902be4629432e704438d999e

**Comment by TheAwoken** [comment]
Thanks Andrew,
it worked.
I just pasted the code into my child theme function. (hope this is good :-)

**Comment by andrewlimaza** [comment]
You're welcome, yea that's fine! :)

Have a great day further.
