### ISSUE TITLE
Feature request: Enter specific group after purchase a specific product?

### ISSUE THREAD

**Issue by alexlii1971** [strangerstudios/pmpro-buddypress#6]
Hello,

Great:

I am looking for an similar buddypress add-on to support that customer can have permission or got permission to enter specific BP group or groups or automatically after they purchase a specific Woocormerce product. 

does it support? if not, please take this as feature request.

Thanks.

Alex

**Comment by ideadude** [comment]
There is probably a better way to do directly in WooCommerce. But this add on allows you to auto add people to Groups based on their Membership Level. So if you are using our pmpro-woocommerce plugin to give users membership levels when they purchase products, it will then add them to the group. Note that the one membership per user limitation applies.

This pmpro-buddypress plugin will launch officially this week. We're finalizing some things and it's still a bit buggy.
