### ISSUE TITLE
Feature Request: Limit/restrict amount of groups allowed to create

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-buddypress#62]
A plus member has requested the ability to limit the number of new groups a user is allowed to create per membership level

**Comment by kimwhite** [comment]
There is a plugin that can restrict creation by "roles"  but would be nice to see it done by Level.
https://wordpress.org/plugins/limit-groups-per-user/

**Comment by andrewlimaza** [comment]
I like the idea of doing this via a custom role as a workaround. We should first support 'limitations' of posting per level then extend this into our Add Ons.
