### ISSUE TITLE
Non-member User Settings requires saving settings before implemented.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-buddypress#67]
**Describe the bug**
Memberships > PMPro BuddyPress >> Non-member User Settings When set to No - Lock access to all of BuddyPress has to be saved manually after activation, this option is not automatically applied and one has to save this option from its admin page to activate it.

**To Reproduce**
Steps to reproduce the behavior (Assuming both PMPro and BuddyPress is active and configured):
1. Install and activate pmpro-buddypress
2. Navigate to Memberships > Settings > Pages and generate "Access Restricted" page
3. Navigate to Memberships > PMPro BuddyPress and observe default setting for Non-member User Settings which should be "No - Lock access to all of BuddyPress"
4. Open incognito/private browser window, log in as a non-member user and navigate to BuddyPress pages "/members/", "/groups/" and "/activity/"
5. These pages are viewable by a logged-in non-member.
6. Return to dashboard and navigate to Memberships > PMPro BuddyPress, in the "Non-member User Settings" section click on "Save All Settings" button.
7. Open incognito/private browser window, log in as a non-member user and navigate to BuddyPress pages "/members/", "/groups/" and "/activity/", visiting these pages should now redirect to the "Access Restricted" page as set under PMPro Pages

**Expected behavior**
BuddyPress lockdown for non-members was expected to be active on activation of the Paid Memberships Pro - BuddyPress Add On

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro, PMPro BuddyPress and BuddyPress plugins are active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

- Server: Apache
- PHP: 7.3.5
- DB: MySQL 8.0.16
- WordPress: 5.4.2
- BuddyPress v6.0.0
- Paid Memberships Pro v2.3.4
- Paid Memberships Pro - BuddyPress Add On v1.2.5

</details>

**Comment by alecrolla** [comment]
hello is still an issue? Or you find a way to fix it?
