### ISSUE TITLE
BuddyPress user pages still accessible when Lock access to all of BuddyPress set.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-buddypress#68]
**Describe the bug**
When Non-member User Settings is set to "No - Lock access to all of BuddyPress" non-member logged in users can still access their own BuddyPress user page.

**To Reproduce**
Steps to reproduce the behavior (Assuming both PMPro and BuddyPress is active and configured):

1. Install and activate pmpro-buddypress
2. Navigate to Memberships > Settings > Pages and generate "Access Restricted" page
3. Navigate to Memberships > PMPro BuddyPress and observe default setting for Non-member User Settings which should be "No - Lock access to all of BuddyPress"
4. Navigate to Users > Add New and create 2 users with usernames "user_1". The user has no membership level.
5. Log in as ueser_1 and navigate to "/members/user_1/"
6. User's BuddyPress Profile is available for user to view and edit. The BuddyPress profile tabs that correctly redirects to the Access Restricted page are the "Messages" and "Groups" tabs.

**Expected behavior**
No - Lock access to all of BuddyPress should restrict access to any and all of BuddyPress for non-members.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro, PMPro BuddyPress and BuddyPress plugins are active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

- Server: Apache
- PHP: 7.3.5
- DB: MySQL 8.0.16
- WordPress: 5.4.2
- BuddyPress v6.0.0
- Paid Memberships Pro v2.3.4
- Paid Memberships Pro - BuddyPress Add On v1.2.5

</details>

**Comment by andrewlimaza** [comment]
The reason this happens is that some plugins like BuddyBoss redirects user's to their own profile page until they update information. I don't see us resolving this as it's quite difficult to figure out all cases and Add On integrations.

A workaround would be to write your own template_redirect gist to redirect away from their own profile page to a landing page.
