### ISSUE TITLE
Logic in pmpro_bp_is_member_directory_locked() is incorrect.

### ISSUE THREAD

**Issue by jasonful** [strangerstudios/pmpro-buddypress#70]
There are 2 problems with pmpro_bp_is_member_directory_locked():

1) If $non_user_options['pmpro_bp_restrictions'] == PMPROBP_LOCK_ALL_ACCESS && $non_user_options['pmpro_bp_member_directory'] == true
then pmpro_bp_is_member_directory_locked() will return false (unlocked) even though it *is* locked because of the PMPROBP_LOCK_ALL_ACCESS.

2) Why is this function checking the "non user" options anyway?  It should be checking *every* level to see if *any* of them locked the Member Directory.

**Comment by ideadude** [comment]
Hi, Jason.

The logic in the pmpro_bp_is_member_directory_locked() function seems different than what you posted here. I don't see recent changes to that file, so it has been this way for a while I think.

```
if( $non_user_options['pmpro_bp_restrictions'] != PMPROBP_GIVE_ALL_ACCESS
	&& ! $non_user_options['pmpro_bp_member_directory'] ) {
	return true;
} else {
	return false;
}
```

It is confusing though and the wording on the function is misleading. The function is only used here:
https://github.com/strangerstudios/pmpro-buddypress/blob/dev/includes/directory.php#L20-L23

And the idea is that if the non-member settings are set so non-members have access to everything or non-members are included in the directory, then we can bail out of that filter and don't have to figure out which members are in or out of the directory.

There isn't a setting to hide the directory itself from certain levels. The settings add or exclude users to the directory.

If you let us know what you are trying to do, we can keep it in mind for a later feature/setting or figure out custom code to help you.

Thanks. Let me know if I'm missing something.

**Comment by jasonful** [comment]
The code I listed was not source code; it was a set of boolean conditions that expose the bug.  And the bug is still there.

(Those boolean conditions happen when the admin goes to the admin page and sets "Include in Member Directory" to "Yes" and then sets "Unlock Buddypress?" to "No - Lock Access to All of BuddyPress".  One would expect the "Lock Access" setting to overrule the "Include in Member Directory" setting, especially since you can't even *see* that setting once you set "Lock Access".  But because of the code you listed, it does *not* overrule it.  The invisible setting wins out.)
