### ISSUE TITLE
pmpro_bp_get_members_in_directory() is not compatible with Approvals addon

### ISSUE THREAD

**Issue by jasonful** [strangerstudios/pmpro-buddypress#71]
pmpro_bp_get_members_in_directory() is not compatible with the "Approval Process for Membership" addon because it goes straight to the SQL database and ignores whether a user has been approved.  (In other words, it bypasses the pmpro_has_membership_level filter.)  
This means denied and pending users show up in the Member Directory.

**Comment by andrewlimaza** [comment]
Updating this, here is the PR that resolves this issue. You may pull this into your Approvals plugin - we decided that this integration would be better to be handled inside the Approvals Add On.
