### ISSUE TITLE
debug please

### ISSUE THREAD

**Issue by alexlii1971** [strangerstudios/pmpro-buddypress#8]
Hello

Thanks for great work, It will show debug message once it was activated:

Notice: Undefined property: stdClass::$groups in /var/www/lovcour.com/htdocs/wp-content/plugins/pmpro-buddypress-master/includes/restrictions.php on line 149

Notice: Trying to get property of non-object in /var/www/lovcour.com/htdocs/wp-content/plugins/pmpro-buddypress-master/includes/restrictions.php on line 149

Here is screenshot:

http://prntscr.com/i2gylr

it will also cause the frontend style mess.

Thanks.

Alex

**Comment by ideadude** [comment]
Fixed in this commit. Thanks for the heads up: https://github.com/strangerstudios/pmpro-buddypress/commit/4b3b8644e9f31be48add652ad29b2aa8394472df
