### ISSUE TITLE
more that one group disallow

### ISSUE THREAD

**Issue by alexlii1971** [strangerstudios/pmpro-buddypress#9]
Hello,

If a customer placed an order with more than one membership products, the customer will only join one group.

Any way to allow join more that one group at the same time please?

Thank, and have a nice day.

Alex

**Comment by ideadude** [comment]
This is a limitation of PMPro. We have a plugin to allow for multiple memberships per user, but it's not yet compatible with our other add ons, including PMPro BuddyPress.

https://github.com/strangerstudios/pmpro-multiple-memberships-per-user

I'll keep an eye out RE what's needed to become compatible. It's likely that the addon won't launch with that compatibility, but we'll work on it soon after.

If you need this functionality now, it is often easier to custom code a solution to work on one specific website vs generally in the addon. You can try to find a developer here https://www.paidmembershipspro.com/developers/

**Comment by alexlii1971** [comment]
Thanks,

FYI, you might like also check this conversation, 
https://wordpress.org/support/topic/pmpro-buddypress-add-on/#post-10087286

since I did not found any differences for multiple memberships levels if pmpro-multiple-memberships-per-user is activated or not.
