### ISSUE TITLE
BuddyPress - Pages settings for Registration get blocked by PMPro

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-buddypress#90]
**Describe the bug**
When using BuddyPress and setting up the Registration page point to the Levels page (or any page). The page is considered part of BuddyPress and becomes restricted.

**To Reproduce**
1. Go to Memberships > PMPro BuddyPress - Unlock BuddyPress - "No, Lock Access to all of BuddyPress" or "Yes, specific features"
2. Go to Dashboard > Settings > BuddyPress - "Pages" tab.
3. See "Registration" pages.
4. Assign Levels Page (or any page).
5. Page becomes restricted. The user is redirected to a "restricted" page.

**Screenshots**
![Screen Shot 2022-04-26 at 11 11 41 AM](https://user-images.githubusercontent.com/8083630/165334224-75c70f2f-74b7-4885-a9f4-27e53631e990.png)

**Expected behavior**
The page defined here should be public and not restricted by PMPro.

Does not apply when using BuddyBoss.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WP: 5.9.3
BP: 10.2.0 
PMPro BP integration: 1.2.7 

</details>

**Comment by andrewlimaza** [comment]
I found this is due to the PMPro BuddyPress option for 'Register Page' set to PMPro levels page.

**Comment by andrewlimaza** [comment]
Looking into this, it's got to do with a combination of settings as mentioned. The only way I could replicate this is:

1. Set the BuddyPress register page to "Levels".
2. Set the Registration option to use PMPro Levels page.
![Screen Shot 2022-05-03 at 11 38 55](https://user-images.githubusercontent.com/12629136/166432813-a3f20fa9-9d64-491c-b22e-0e6131b0504d.png)

![Screen Shot 2022-05-03 at 11 38 48](https://user-images.githubusercontent.com/12629136/166432820-cbd218d0-c7c0-459b-9dfe-f75f14728dfb.png)
