### ISSUE TITLE
levels page not accessible after 1.2.8 upgrade

### ISSUE THREAD

**Issue by FrancYescO** [strangerstudios/pmpro-buddypress#94]
**Describe the bug**
1.2.8 breaks my registration flow: will be not possibile to access the levels page after an user registration as you will be redirected to homepage (or bp registration page if not logged in)

**To Reproduce**
1 enable buddypress as registration page
2 register an account (without getting a pmp pro level)
3 try to go to pmp pro levels page /membership-account/membership-levels/

the same flow work correctly in 1.2.7

solution here https://github.com/strangerstudios/pmpro-buddypress/pull/93

**Comment by andrewlimaza** [comment]
This has been merged into dev, for now you may pull the dev branch to update your version to the pre-release.
